<?php
/**
 * Installation Wizard API
 * Handles database setup and admin user creation
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    exit(0);
}

// Check if already installed
function isInstalled(): bool {
    $configFile = __DIR__ . '/../api/config.php';
    if (!file_exists($configFile)) {
        return false;
    }
    
    $content = file_get_contents($configFile);
    return strpos($content, 'your_database_name') === false;
}

// Test database connection
function testConnection(string $host, string $name, string $user, string $pass): array {
    try {
        $pdo = new PDO(
            "mysql:host={$host};charset=utf8mb4",
            $user,
            $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        
        // Check if database exists
        $stmt = $pdo->query("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = " . $pdo->quote($name));
        $dbExists = $stmt->fetch() !== false;
        
        return ['success' => true, 'dbExists' => $dbExists];
    } catch (PDOException $e) {
        return ['success' => false, 'error' => $e->getMessage()];
    }
}

// Create database if it doesn't exist
function createDatabase(string $host, string $name, string $user, string $pass): array {
    try {
        $pdo = new PDO(
            "mysql:host={$host};charset=utf8mb4",
            $user,
            $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        
        return ['success' => true];
    } catch (PDOException $e) {
        return ['success' => false, 'error' => $e->getMessage()];
    }
}

// Import schema
function importSchema(string $host, string $name, string $user, string $pass): array {
    try {
        $pdo = new PDO(
            "mysql:host={$host};dbname={$name};charset=utf8mb4",
            $user,
            $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        
        // Read schema file
        $schemaFile = __DIR__ . '/../../database/schema.sql';
        if (!file_exists($schemaFile)) {
            return ['success' => false, 'error' => 'Schema file not found'];
        }
        
        $schema = file_get_contents($schemaFile);
        
        // Execute schema (split by semicolons for multiple statements)
        $statements = array_filter(array_map('trim', explode(';', $schema)));
        
        foreach ($statements as $statement) {
            if (!empty($statement)) {
                $pdo->exec($statement);
            }
        }
        
        return ['success' => true];
    } catch (PDOException $e) {
        return ['success' => false, 'error' => $e->getMessage()];
    }
}

// Create admin user
function createAdmin(string $host, string $name, string $user, string $pass, string $email, string $adminName, string $adminPass): array {
    try {
        $pdo = new PDO(
            "mysql:host={$host};dbname={$name};charset=utf8mb4",
            $user,
            $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        
        // Check if user already exists
        $stmt = $pdo->prepare("SELECT id FROM users WHERE email = ?");
        $stmt->execute([$email]);
        if ($stmt->fetch()) {
            return ['success' => false, 'error' => 'User with this email already exists'];
        }
        
        // Create admin user
        $hashedPassword = password_hash($adminPass, PASSWORD_BCRYPT);
        $stmt = $pdo->prepare("INSERT INTO users (email, name, password_hash, role, status) VALUES (?, ?, ?, 'admin', 'active')");
        $stmt->execute([$email, $adminName, $hashedPassword]);
        
        return ['success' => true];
    } catch (PDOException $e) {
        return ['success' => false, 'error' => $e->getMessage()];
    }
}

// Generate random JWT secret
function generateSecret(): string {
    return bin2hex(random_bytes(32));
}

// Update config file
function updateConfig(string $host, string $name, string $user, string $pass, string $jwtSecret, string $adminEmail): array {
    $configFile = __DIR__ . '/../api/config.php';
    
    if (!is_writable(dirname($configFile))) {
        return ['success' => false, 'error' => 'Config directory is not writable'];
    }
    
    $config = "<?php
/**
 * Configuration File
 * Auto-generated by Installation Wizard
 */

// Database Configuration
define('DB_HOST', '{$host}');
define('DB_NAME', '{$name}');
define('DB_USER', '{$user}');
define('DB_PASS', '{$pass}');

// Security Configuration
define('JWT_SECRET', '{$jwtSecret}');
define('JWT_EXPIRY', 86400 * 7); // Token expiry in seconds (7 days)

// Application Settings
define('APP_NAME', 'Agency Dashboard');
define('ADMIN_EMAIL', '{$adminEmail}');

// CORS Settings
define('ALLOWED_ORIGINS', '*'); // Change to your domain in production

// Debug Mode (set to false in production)
define('DEBUG_MODE', false);
";

    if (file_put_contents($configFile, $config) === false) {
        return ['success' => false, 'error' => 'Failed to write config file'];
    }
    
    return ['success' => true];
}

// Handle requests
$action = $_GET['action'] ?? '';
$input = json_decode(file_get_contents('php://input'), true) ?? [];

switch ($action) {
    case 'check':
        echo json_encode(['installed' => isInstalled()]);
        break;
        
    case 'test':
        if (empty($input['host']) || empty($input['name']) || empty($input['user'])) {
            echo json_encode(['success' => false, 'error' => 'Missing required fields']);
            break;
        }
        echo json_encode(testConnection($input['host'], $input['name'], $input['user'], $input['pass'] ?? ''));
        break;
        
    case 'install':
        if (isInstalled()) {
            echo json_encode(['success' => false, 'error' => 'Application is already installed']);
            break;
        }
        
        $required = ['host', 'name', 'user', 'adminEmail', 'adminName', 'adminPass'];
        foreach ($required as $field) {
            if (empty($input[$field])) {
                echo json_encode(['success' => false, 'error' => "Missing required field: {$field}"]);
                exit;
            }
        }
        
        $host = $input['host'];
        $name = $input['name'];
        $user = $input['user'];
        $pass = $input['pass'] ?? '';
        $adminEmail = $input['adminEmail'];
        $adminName = $input['adminName'];
        $adminPass = $input['adminPass'];
        
        // Step 1: Create database
        $result = createDatabase($host, $name, $user, $pass);
        if (!$result['success']) {
            echo json_encode(['success' => false, 'error' => 'Failed to create database: ' . $result['error']]);
            break;
        }
        
        // Step 2: Import schema
        $result = importSchema($host, $name, $user, $pass);
        if (!$result['success']) {
            echo json_encode(['success' => false, 'error' => 'Failed to import schema: ' . $result['error']]);
            break;
        }
        
        // Step 3: Create admin user
        $result = createAdmin($host, $name, $user, $pass, $adminEmail, $adminName, $adminPass);
        if (!$result['success']) {
            echo json_encode(['success' => false, 'error' => 'Failed to create admin: ' . $result['error']]);
            break;
        }
        
        // Step 4: Update config
        $jwtSecret = generateSecret();
        $result = updateConfig($host, $name, $user, $pass, $jwtSecret, $adminEmail);
        if (!$result['success']) {
            echo json_encode(['success' => false, 'error' => 'Failed to update config: ' . $result['error']]);
            break;
        }
        
        echo json_encode(['success' => true, 'message' => 'Installation completed successfully']);
        break;
        
    default:
        echo json_encode(['error' => 'Invalid action']);
}
